---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: seccompprofiles.seccomp-operator.k8s-sigs.io # ??
spec:
  group: seccomp-operator.k8s-sigs.io # need to decide a group for this - can't use *.k8s.io https://github.com/kubernetes/enhancements/pull/1111
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: |
            SeccompProfile is a cluster level specification for a seccomp profile.

            See https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp
          type: object
          properties:
            spec:
              description: Specification of the seccomp profile.
              type: object
              properties:
                defaultAction:
                  description: the default action for seccomp.
                  type: string
                  pattern: "^SCMP_ACT_(KILL|KILL_PROCESS|KILL_THREAD|TRAP|ERRNO|TRACE|ALLOW|LOG)$"
                architectures:
                  description: the architecture used for system calls.
                  type: array
                  items:
                    type: string
                    pattern: "^SCMP_ARCH_(X86,X86_64,X32,ARM,AARCH64,MIPS,MIPS64,MIPS64N32,MIPSEL,MIPSEL64,MIPSEL64N32,PPC,PPC64,PPC64LE,S390,S390X,PARISC,PARISC64,RISCV64)$"
                flags:
                  description: list of flags to use with seccomp(2)
                  type: array
                  items:
                    type: string
                    pattern: "^SECCOMP_FILTER_FLAG_(TSYNC|LOG|SPEC_ALLOW)$"
                syscalls:
                  description: match a syscall in seccomp. While this property is OPTIONAL, some values of defaultAction are not useful without syscalls entries. For example, if defaultAction is SCMP_ACT_KILL and syscalls is empty or unset, the kernel will kill the container process on its first syscall.
                  type: array
                  items:
                    type: object
                    properties:
                      names:
                        description: the names of the syscalls.
                        type: array
                        items:
                          type: string
                      action:
                        description: the action for seccomp rules.
                        type: string
                        pattern: "^SCMP_ACT_(KILL|KILL_PROCESS|KILL_THREAD|TRAP|ERRNO|TRACE|ALLOW|LOG)$"
                      errnoRet:
                        description: the errno return code to use. Some actions like SCMP_ACT_ERRNO and SCMP_ACT_TRACE allow to specify the errno code to return.
                        type: string
                      args:
                        description:  the specific syscall in seccomp
                        type: array
                        items:
                          type: object
                          properties:
                            index:
                              description: the index for syscall arguments in seccomp.
                              type: integer
                              minimum: 0
                            value:
                              description: the value for syscall arguments in seccomp.
                              type: integer
                              minimum: 0
                            valueTwo:
                              description: the value for syscall arguments in seccomp.
                              type: integer
                              minimum: 0
                            op:
                              description: the operator for syscall arguments in seccomp.
                              type: string
                              pattern: "^SCMP_CMP_(NE|LT|LE|EQ|GE|GT|MASKED_EQ)$"
                          required:
                          - index
                          - op
                    required:
                    - names
                    - action
              required:
              - defaultAction
  scope: Namespaced
  names:
    plural: seccompprofiles
    singular: seccompprofile
    kind: SeccompProfile
    shortNames:
    - sp
