---
apiVersion: v1
kind: Namespace
metadata:
  name: seccomp-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seccomp-operator
  namespace: seccomp-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-creator
  namespace: seccomp-operator
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-creator-binding
subjects:
- kind: ServiceAccount
  name: seccomp-operator
  namespace: seccomp-operator
roleRef:
  kind: ClusterRole
  name: event-creator-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seccomp-profile-reader
rules:
- apiGroups: ["seccomp-operator.x-k8s.io"]
  resources: ["seccompprofiles"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seccomp-profile-reader-binding
subjects:
- kind: ServiceAccount
  name: seccomp-operator
  namespace: seccomp-operator
roleRef:
  kind: ClusterRole
  name: seccomp-profile-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-reader
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-reader-binding
subjects:
- kind: ServiceAccount
  name: seccomp-operator
  namespace: seccomp-operator
roleRef:
  kind: ClusterRole
  name: crd-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seccomp-profile-creator
  namespace: seccomp-operator
rules:
- apiGroups: ["seccomp-operator.x-k8s.io"]
  resources: ["seccompprofiles"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seccomp-profile-creator-binding
  namespace: seccomp-operator
subjects:
- kind: ServiceAccount
  name: seccomp-operator
  namespace: seccomp-operator
roleRef:
  kind: Role
  name: seccomp-profile-creator
  apiGroup: rbac.authorization.k8s.io
