apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: seccomp-operator
  name: seccomp-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: seccomp-operator
  name: seccomp-operator
  namespace: seccomp-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: seccomp-operator
  name: config-map-reader
  namespace: seccomp-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - seccomp-operator.k8s-sigs.io
  resources:
  - seccompprofiles
  verbs:
  - create
  - patch
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: seccomp-operator
  name: config-map-reader-binding
  namespace: seccomp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: config-map-reader
subjects:
- kind: ServiceAccount
  name: seccomp-operator
  namespace: seccomp-operator
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: seccomp-operator
  name: seccomp-operator
  namespace: seccomp-operator
spec:
  selector:
    matchLabels:
      app: seccomp-operator
      name: seccomp-operator
  template:
    metadata:
      annotations:
        container.seccomp.security.alpha.kubernetes.io/seccomp-operator: localhost/seccomp-operator.json
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: seccomp-operator
        name: seccomp-operator
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: gcr.io/k8s-staging-seccomp-operator/seccomp-operator:latest
        imagePullPolicy: Always
        name: seccomp-operator
        resources:
          limits:
            cpu: 300m
            ephemeral-storage: 200Mi
            memory: 128Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 2000
          runAsUser: 2000
        volumeMounts:
        - mountPath: /var/lib/kubelet/seccomp/operator
          name: host-operator-volume
      initContainers:
      - args:
        - |
          set -euo pipefail

          if [ ! -d $KUBELET_SECCOMP_ROOT ]; then
            /bin/mkdir -m 0744 -p $KUBELET_SECCOMP_ROOT
          fi

          /bin/mkdir -p $OPERATOR_ROOT
          /bin/chmod 0744 $OPERATOR_ROOT

          if [ ! -L $OPERATOR_SYMLINK ]; then
            /bin/ln -s $OPERATOR_ROOT $OPERATOR_SYMLINK
          fi

          /bin/chown -R 2000:2000 $OPERATOR_ROOT
          cp -f -v /opt/seccomp-profiles/* $KUBELET_SECCOMP_ROOT
        command:
        - bash
        - -c
        env:
        - name: KUBELET_SECCOMP_ROOT
          value: /var/lib/kubelet/seccomp
        - name: OPERATOR_SYMLINK
          value: $(KUBELET_SECCOMP_ROOT)/operator
        - name: OPERATOR_ROOT
          value: /var/lib/seccomp-operator
        image: bash:5.0
        name: non-root-enabler
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 50Mi
            memory: 64Mi
          requests:
            cpu: 100m
            ephemeral-storage: 10Mi
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - FOWNER
            - FSETID
            - DAC_OVERRIDE
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/lib
          name: host-varlib-volume
        - mountPath: /opt/seccomp-profiles
          name: profile-configmap-volume
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: seccomp-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib
          type: Directory
        name: host-varlib-volume
      - hostPath:
          path: /var/lib/seccomp-operator
          type: DirectoryOrCreate
        name: host-operator-volume
      - configMap:
          name: seccomp-operator-profile
        name: profile-configmap-volume
---
apiVersion: v1
data:
  seccomp-operator.json: |
    {
      "defaultAction": "SCMP_ACT_ERRNO",
      "architectures": ["SCMP_ARCH_X86_64", "SCMP_ARCH_X86", "SCMP_ARCH_X32"],
      "syscalls": [
        {
          "names": [
            "accept4",
            "arch_prctl",
            "bind",
            "brk",
            "clone",
            "close",
            "connect",
            "epoll_create1",
            "epoll_ctl",
            "epoll_pwait",
            "execve",
            "exit",
            "exit_group",
            "fcntl",
            "fstat",
            "futex",
            "getcwd",
            "getgid",
            "getpeername",
            "getpgrp",
            "getpid",
            "getppid",
            "getrandom",
            "getsockname",
            "getsockopt",
            "gettid",
            "getuid",
            "listen",
            "madvise",
            "membarrier",
            "mkdirat",
            "mlock",
            "mmap",
            "mprotect",
            "nanosleep",
            "newfstatat",
            "open",
            "openat",
            "pipe2",
            "pread64",
            "read",
            "readlinkat",
            "rt_sigaction",
            "rt_sigprocmask",
            "rt_sigreturn",
            "sched_getaffinity",
            "sched_yield",
            "setgid",
            "setsockopt",
            "set_tid_address",
            "setuid",
            "sigaltstack",
            "socket",
            "tgkill",
            "uname",
            "write"
          ],
          "action": "SCMP_ACT_ALLOW"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app: seccomp-operator
  name: seccomp-operator-profile
  namespace: seccomp-operator
---
apiVersion: v1
data:
  nginx-1.19.1.json: |-
    {
      "defaultAction": "SCMP_ACT_ERRNO",
      "architectures":[
          "SCMP_ARCH_X86_64",
          "SCMP_ARCH_X86",
          "SCMP_ARCH_X32"
      ],
      "syscalls": [
        {
          "names": [
            "accept4",
            "access",
            "arch_prctl",
            "bind",
            "brk",
            "capget",
            "capset",
            "chdir",
            "chown",
            "clone",
            "close",
            "connect",
            "dup2",
            "epoll_create",
            "epoll_ctl",
            "epoll_pwait",
            "epoll_wait",
            "eventfd2",
            "execve",
            "exit",
            "exit_group",
            "faccessat",
            "fadvise64",
            "fchdir",
            "fchown",
            "fcntl",
            "fgetxattr",
            "fsetxattr",
            "fstat",
            "fstatfs",
            "futex",
            "getcwd",
            "getdents",
            "getdents64",
            "getegid",
            "geteuid",
            "getgid",
            "getpid",
            "getppid",
            "getrlimit",
            "getuid",
            "ioctl",
            "io_setup",
            "listen",
            "lseek",
            "mkdir",
            "mmap",
            "mprotect",
            "munmap",
            "nanosleep",
            "newfstatat",
            "open",
            "openat",
            "pipe",
            "prctl",
            "pread64",
            "prlimit64",
            "pwrite64",
            "read",
            "recvfrom",
            "recvmsg",
            "rename",
            "rt_sigaction",
            "rt_sigprocmask",
            "rt_sigreturn",
            "rt_sigsuspend",
            "sched_getaffinity",
            "seccomp",
            "sendfile",
            "sendmsg",
            "setgid",
            "setgroups",
            "setitimer",
            "set_robust_list",
            "setsockopt",
            "set_tid_address",
            "setuid",
            "sigaltstack",
            "socket",
            "socketpair",
            "stat",
            "statfs",
            "sysinfo",
            "umask",
            "uname",
            "unlink",
            "utimensat",
            "wait4",
            "write",
            "writev"
          ],
          "action": "SCMP_ACT_ALLOW",
          "args": [],
          "comment": "",
          "includes": {},
          "excludes": {}
        }
      ]
    }
kind: ConfigMap
metadata:
  annotations:
    seccomp.security.kubernetes.io/profile: "true"
  labels:
    app: seccomp-operator
  name: default-profiles
  namespace: seccomp-operator
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: seccompprofiles.seccomp-operator.k8s-sigs.io # ??
spec:
  group: seccomp-operator.k8s-sigs.io # need to decide a group for this - can't use *.k8s.io https://github.com/kubernetes/enhancements/pull/1111
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: |
            SeccompProfile is a cluster level specification for a seccomp profile.

            See https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp
          type: object
          properties:
            spec:
              description: Specification of the seccomp profile.
              type: object
              properties:
                defaultAction:
                  description: the default action for seccomp.
                  type: string
                  pattern: "^SCMP_ACT_(KILL|KILL_PROCESS|KILL_THREAD|TRAP|ERRNO|TRACE|ALLOW|LOG)$"
                architectures:
                  description: the architecture used for system calls.
                  type: array
                  items:
                    type: string
                    pattern: "^SCMP_ARCH_(X86,X86_64,X32,ARM,AARCH64,MIPS,MIPS64,MIPS64N32,MIPSEL,MIPSEL64,MIPSEL64N32,PPC,PPC64,PPC64LE,S390,S390X,PARISC,PARISC64,RISCV64)$"
                syscalls:
                  description: match a syscall in seccomp. While this property is OPTIONAL, some values of defaultAction are not useful without syscalls entries. For example, if defaultAction is SCMP_ACT_KILL and syscalls is empty or unset, the kernel will kill the container process on its first syscall.
                  type: array
                  items:
                    type: object
                    properties:
                      names:
                        description: the names of the syscalls.
                        type: array
                        items:
                          type: string
                      action:
                        description: the action for seccomp rules.
                        type: string
                        pattern: "^SCMP_ACT_(KILL|KILL_PROCESS|KILL_THREAD|TRAP|ERRNO|TRACE|ALLOW|LOG)$"
                      args:
                        description:  the specific syscall in seccomp
                        type: array
                        items:
                          type: object
                          properties:
                            index:
                              description: the index for syscall arguments in seccomp.
                              type: integer
                              minimum: 0
                            value:
                              description: the value for syscall arguments in seccomp.
                              type: integer
                              minimum: 0
                            valueTwo:
                              description: the value for syscall arguments in seccomp.
                              type: integer
                              minimum: 0
                            op:
                              description: the operator for syscall arguments in seccomp.
                              type: string
                              pattern: "^SCMP_CMP_(NE|LT|LE|EQ|GE|GT|MASKED_EQ)$"
                          required:
                          - index
                          - op
                      #flags:
                      #  description: ? # in OCI spec but not in current examples
                      #  type: array
                      #comment:
                      #  description: ? # not in OCI spec
                      #  type: string
                      #includes:
                      #  description: ? # not in OCI spec
                      #  type: object
                      #excludes:
                      #  description: ? # not in OCI spec
                      #  type: object
                    required:
                    - names
                    - action
              required:
              - defaultAction
  scope: Namespaced
  names:
    plural: seccompprofiles
    singular: seccompprofile
    kind: SeccompProfile
    shortNames:
    - sp
