---
apiVersion: seccomp-operator.k8s-sigs.io/v1alpha1
kind: SeccompProfile
metadata:
  name: profile-block
spec:
  defaultAction: "SCMP_ACT_ERRNO"
---
apiVersion: seccomp-operator.k8s-sigs.io/v1alpha1
kind: SeccompProfile
metadata:
  name: profile-complain
spec:
  defaultAction: "SCMP_ACT_LOG"
---
apiVersion: seccomp-operator.k8s-sigs.io/v1alpha1
kind: SeccompProfile
metadata:
  name: profile-allow
spec:
  defaultAction: "SCMP_ACT_ALLOW"
