# This is the cluster wide seccomp-operator deployment, which listens for
# SeccompProfiles on all namespaces
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: default-seccomp-profiles
    path: default-seccomp-profiles.yaml
