# This is the namespaced deployment, which only watches SeccompProfiles for one
# namespace.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../cluster

patchesStrategicMerge:
  - daemonset.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: event-creator
    path: clusterrole.yaml

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: seccomp-profile-reader
    path: clusterrole.yaml

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: event-creator-binding
    path: clusterrolebinding.yaml

  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: seccomp-profile-reader-binding
    path: clusterrolebinding.yaml
